merge rel2-alida in main
A-lida/lab_elettronica pull request #1
Opened 2024-11-23 00:06 UTC by A-lida

Ho lavorato sulla sub-section acquisizione.tex aggiungendo una bozza dell'apparato sperimentale e le tabelle delle misure dei diodi. Ho implementato anche l'abstract.

2024-11-24 17:59 UTC, Pe13 requested changes
A parte le cose che ti ho commentato, tutto bene 👌🏻

2024-11-24 17:59 UTC, Pe13 commented on lab1/relazione/src/main.tex
> +    Si riportano rispettivamente i valori attesi, con le relative incertezze associate, rispettivamente per il diodo al silicio e al germanio:
Avrei detto rispettivamente un altro paio di volte 😝

2024-11-24 17:59 UTC, Pe13 commented on lab1/relazione/src/sections/acquisizione.tex
> +  Il circuito in \textit{Fig.\!\!\! 1} è stato realizzato su una millefori, ed è stato alimentato mediante un $alimentatore\, di\, bassa\, tensione$, erogante una differenza di potenziale di +5V.
Hai usato la math mode per fare il testo corsivo?
Per quello hanno fatto \textit{}

Edit: sono tornato qui dopo aver visto che sotto l'hai usato, ti pesava cambiarlo?? (a questo punto inizio a prendere in considerazione l'ipotesi che ci sia un buon motivo sotto)

2024-11-24 17:59 UTC, Pe13 commented on lab1/relazione/src/sections/acquisizione.tex
> +  Le misure di tensione sono state effettuante mediante l'ausilio di un $oscilloscopio$ con risoluzione dipendente dal fondoscala utilizzato e di un $multimetro\, digitale$, avente risoluzione pari a
La risoluzione in mV manca perché non la sai o perché te la sei dimenticata?

2024-11-24 18:13 UTC, Pe13 commented
Altra cosa, negli align dell'abstract devi togliere i dollari.
A te così com'è funziona? Perché a me no e dovrebbe essere così, dato che se non ricordo male, negli ambienti align sei già di default in math mode

2024-11-24 18:21 UTC, Pe13 commented
Altra cosa, non starei a mettere tutte quelle parentesi nelle tabelle (la doppia riga ai lati sono volute?)

2024-11-25 10:08 UTC, A-lida reviewed
Ho sistemato le cose che avevi esplicitamente commentato, rimane solo da inserire la risoluzione in mV poichè non la ricordo

2024-11-25 10:09 UTC, merged